title: Project prime prediction
description: >
  <br>
   Prediction of insurance costs 
  <br>
#remote_theme: pages-themes/slate@v0.2.0
#remote_theme: pages-themes/architect@v0.2.0
#plugins:
#- jekyll-remote-theme
github:
    is_project_page: true
show_downloads: false
theme: jekyll-theme-cayman

