title: Project prime prediction
logo: /assets/img/triangle.jpg
description: >
  <br>
   Prediction of insurance costs 
  <br>
#remote_theme: pages-themes/slate@v0.2.0
#remote_theme: pages-themes/architect@v0.2.0
#plugins:
#- jekyll-remote-theme
theme: jekyll-theme-cayman
repository: https://github.com/AhmedProj/PrimePredict.git
