title: Project Prime Prediction
logo: /assets/img/triangle.jpg
description: >
  <br>
  Prediction of insurance costs
  <br>
  <style>
    body { background-color: #f4f4f9; }
    h1 { color: #333333; font-family: 'Arial', sans-serif; }
    nav { background-color: #ffffff; border-bottom: 1px solid #ccc; }
    a { color: #1a0dab; text-decoration: none; }
    a:hover { text-decoration: underline; }
  </style>
theme: jekyll-theme-cayman
